version: '3.8'

networks:
    backend:
        driver: bridge

services:

    product_service:
        env_file: ./.env
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        restart: always
        volumes:
            - ${PRODUCT_SERVICE_DOCUMENT_ROOT}:/var/www/html/
        ports:
            - ${PRODUCT_APACHE_HOST_HTTP_PORT}:80
            - ${PRODUCT_APACHE_HOST_HTTPS_PORT}:443
            - 9001:9000
        environment:
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - TZ=Asia/Karachi
        networks:
            - backend


    notification_service:
        env_file: ./.env
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        restart: always
        volumes:
            - ${NOTIFICATION_SERVICE_DOCUMENT_ROOT}:/var/www/html
        ports:
            - ${NOTIFICATION_APACHE_HOST_HTTP_PORT}:80
            - ${NOTIFICATION_APACHE_HOST_HTTPS_PORT}:443
            - 9002:9000
        environment:
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - TZ=Asia/Karachi
        networks:
            - backend

    db:
        env_file: ./.env
        container_name: db
        image: mariadb:latest
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MARIADB_USER=${MYSQL_DB_USER}
            - MARIADB_PASSWORD=${MYSQL_DB_PASSWORD}
            - MARIADB_DATABASE=${MYSQL_DB_DATABASE}
        ports:
            - 3306:3306
        networks:
            - backend

